#!/bin/sh
docker run \
    --name scala_samples \
    --user scala-user \
    -it \
    --rm \
    -v /workspace/projects/scala-samples:/work \
    -e COURSIER_CACHE=/work/.coursier_cache \
    -w /work \
    dev-scala:1 \
    bash
